version: "3"
services:
  redis:
    image: redis:6-alpine
    command: redis-server
  celery-worker:
    env_file:
      - env/common.env
    build: .
    depends_on:
      - redis
    volumes:
      - .:/code
    command: sh -c "cd server && poetry run watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- poetry run celery --app=server.celery.celery_app worker"
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - env/common.env
    volumes:
      - ./database/:/var/lib/postgresql/data/
  flask-server:
    build: .
    env_file:
      - env/common.env
      - env/dev.env
    depends_on:
      - postgres
      - celery-worker
    volumes:
      - .:/code
    command: sh -c "cd server/server && poetry run flask run --host=0.0.0.0"
  reverse:
    hostname: reverse
    image: nginx:1.19
    depends_on:
      - flask-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - .nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/certs/live/reusing.sci.utah.edu/fullchain.pem:/etc/nginx/fullchain.pem
      - /home/ubuntu/certs/live/reusing.sci.utah.edu/privkey.pem:/etc/nginx/privkey.pem
volumes:
  postgres_data:
