name: lint
on:
  push:
    branches-ignore:
      - "main"
jobs:
  test_react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and check Lint
        run: |
          cd app
          yarn install
          yarn lint
  test_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install server
        working-directory: ./server
        run: poetry install
      - name: Lint server with isort
        working-directory: ./server
        run: poetry run isort server/**/*.py
      - name: Lint server with black
        working-directory: ./server
        run: poetry run black server/**/*.py
      - name: Lint server with flake8
        working-directory: ./server
        run: poetry run flake8 server/**/*.py
      - name: Lint server with mypy
        working-directory: ./server
        run: poetry run mypy server/**/*.py
  test_library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install server
        working-directory: ./reapply-workflows
        run: poetry install
      - name: Lint server with isort
        working-directory: ./reapply-workflows
        run: poetry run isort src/**/*.py
      - name: Lint server with black
        working-directory: ./reapply-workflows
        run: poetry run black src/**/*.py
      - name: Lint server with flake8
        working-directory: ./reapply-workflows
        run: poetry run flake8 src/**/*.py
      - name: Lint server with mypy
        working-directory: ./reapply-workflows
        run: poetry run mypy src/**/*.py
